---
# tasks file for /etc/ansible/roles/staged-roles/apache-installation
- name: install apache package
  yum:
          name: httpd
          state: latest
- name: copy index.html file
  copy:
          src: /etc/ansible/file/index.html
          dest: /var/www/html
  notify:
          - restart apache
- name: Start and Enable apache service
  service:
          name: httpd
          state: restarted
          enabled: yes  
